language: android
jdk: oraclejdk8
env:
 global:
    - ANDROID_API_LEVEL=27
    - ANDROID_BUILD_TOOLS_VERSION=31
#The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - extra

#The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

android:
 licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-31.0.1'
    - 'google-gdk-license-.+'
    - 'build-tools-license-30.0.3'
    - 'build-tools-license-.+
    - 'andorid-sdk-license-26.1.1'
    - 'android-sdk-license-.+'
 components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
before_script:
    # Prepare pre-accepted licenses to not be promted at installation
    - mkdir -p "$ANDROID_HOME/licenses"
    - cp ./google-licenses/* "$ANDROID_HOME/licenses/"
script:
    - ./gradlew build check